# Generated by Django 3.2.8 on 2021-10-23 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='acc_num',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
