# Generated by Django 3.2.8 on 2021-10-15 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0002_wallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transfer_type',
            field=models.CharField(choices=[('Expense', 'expense'), ('Income', 'income')], default='Expense', max_length=8),
        ),
    ]
