# Generated by Django 3.2.8 on 2021-10-15 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0004_alter_transaction_to_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transfer_type',
            field=models.CharField(choices=[('Expense', 'Expense'), ('Income', 'Income')], default='Expense', max_length=8),
        ),
    ]
