# Generated by Django 3.2.8 on 2021-10-16 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0010_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='amount',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
