# Generated by Django 3.2.8 on 2021-10-16 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0011_notification_amount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created']},
        ),
        migrations.AddField(
            model_name='transaction',
            name='ref_no',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='trx_id',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
